### ISSUE TITLE
Can't use WindRose via Grafana on website grafana.net

### ISSUE THREAD

**Issue by ghost** [fatcloud/windrose-panel#24]
An unexpected error happened
TypeError: Cannot read properties of undefined (reading 'emit')

    at tn (https://grafana-assets.grafana.net/grafana/8.1.5-35396/public/build/DashboardPage.1a28dcfe04191bd9acd3.js:251:4464)
    at E (https://grafana-assets.grafana.net/grafana/8.1.5-35396/public/build/vendors~app.1a28dcfe04191bd9acd3.js:2:73696)
    at div
    at div
    at div
    at t (https://grafana-assets.grafana.net/grafana/8.1.5-35396/public/build/vendors~app.1a28dcfe04191bd9acd3.js:2:852951)
    at h (https://grafana-assets.grafana.net/grafana/8.1.5-35396/public/build/app.1a28dcfe04191bd9acd3.js:6100:36473)
    at div
    at div
    at on (https://grafana-assets.grafana.net/grafana/8.1.5-35396/public/build/DashboardPage.1a28dcfe04191bd9acd3.js:251:6692)
    at div
    at div
    at wn (https://grafana-assets.grafana.net/grafana/8.1.5-35396/public/build/DashboardPage.1a28dcfe04191bd9acd3.js:322:44)
    at div
    at t (https://grafana-assets.grafana.net/grafana/8.1.5-35396/public/build/DashboardPage.1a28dcfe04191bd9acd3.js:355:1554)
    at div
    at t (https://grafana-assets.grafana.net/grafana/8.1.5-35396/public/build/DashboardPage.1a28dcfe04191bd9acd3.js:355:3507)
    at Jn (https://grafana-assets.grafana.net/grafana/8.1.5-35396/public/build/DashboardPage.1a28dcfe04191bd9acd3.js:355:9139)
    at div
    at div
    at vr (https://grafana-assets.grafana.net/grafana/8.1.5-35396/public/build/DashboardPage.1a28dcfe04191bd9acd3.js:382:2172)
    at E (https://grafana-assets.grafana.net/grafana/8.1.5-35396/public/build/vendors~app.1a28dcfe04191bd9acd3.js:2:73696)
    at div
    at E (https://grafana-assets.grafana.net/grafana/8.1.5-35396/public/build/DashboardPage.1a28dcfe04191bd9acd3.js:432:994)
    at DashboardPage
    at E (https://grafana-assets.grafana.net/grafana/8.1.5-35396/public/build/vendors~app.1a28dcfe04191bd9acd3.js:2:73696)
    at n (https://grafana-assets.grafana.net/grafana/8.1.5-35396/public/build/vendors~app.1a28dcfe04191bd9acd3.js:2:545060)
    at Q (https://grafana-assets.grafana.net/grafana/8.1.5-35396/public/build/app.1a28dcfe04191bd9acd3.js:654:3244)
    at t (https://grafana-assets.grafana.net/grafana/8.1.5-35396/public/build/vendors~app.1a28dcfe04191bd9acd3.js:2:1381705)
    at t (https://grafana-assets.grafana.net/grafana/8.1.5-35396/public/build/vendors~app.1a28dcfe04191bd9acd3.js:2:1383750)
    at main
    at t (https://grafana-assets.grafana.net/grafana/8.1.5-35396/public/build/vendors~app.1a28dcfe04191bd9acd3.js:2:1378310)
    at div
    at la (https://grafana-assets.grafana.net/grafana/8.1.5-35396/public/build/app.1a28dcfe04191bd9acd3.js:3789:1227)
    at h (https://grafana-assets.grafana.net/grafana/8.1.5-35396/public/build/app.1a28dcfe04191bd9acd3.js:6060:20188)
    at dl (https://grafana-assets.grafana.net/grafana/8.1.5-35396/public/build/app.1a28dcfe04191bd9acd3.js:4466:682)
    at ul (https://grafana-assets.grafana.net/grafana/8.1.5-35396/public/build/app.1a28dcfe04191bd9acd3.js:4466:972)
    at l (https://grafana-assets.grafana.net/grafana/8.1.5-35396/public/build/vendors~app.1a28dcfe04191bd9acd3.js:2:71604)
    at Oe (https://grafana-assets.grafana.net/grafana/8.1.5-35396/public/build/app.1a28dcfe04191bd9acd3.js:667:517)

**Comment by ssozonoff** [comment]
I have the same issue

**Comment by kaooooru** [comment]
Same issue

**Comment by Bra1nsen** [comment]
same issue, anything we can do?
